name: Automate infrastructure deployment with terragrunt

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
     
  terragrunt:
    name: Deploy AWS Infrastructure with Terragrunt
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - name: Install Terragrunt
        run: |
          curl -LO https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::023520667418:role/github-actions-terragrunt
          aws-region: eu-west-1

      - name: Terragrunt HCL format check
        working-directory: live
        run: terragrunt hclfmt --terragrunt-check

      - name: Terraform format check
        working-directory: infra
        run: |
          cd modules
          terraform fmt -check -recursive

      - name: Terragrunt validate
        working-directory: live
        run: terragrunt run-all validate --terragrunt-non-interactive

      # We plan only VPC and EKS here because k8s-addons read cluster info before the cluster exists
      - name: Terragrunt Plan EKS and VPC modules
        working-directory: live
        run: |
          cd dev
          terragrunt run --all --queue-exclude-dir k8s-addons --backend-bootstrap plan

      - name: Terragrunt Apply All
        working-directory: live
        run: |
          cd dev
          terragrunt run --all --non-interactive apply
